name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cleanup
        run: sed -i "s/%NAME%/test/g" build.sc
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - name: Setup Mill
        uses: jodersky/setup-mill@v0.2.3
        with:
          mill-version: 0.9.7
      - name: Cache Scala
        uses: coursier/cache-action@v5
      - name: mill Test
        run: mill _.compile
      - name: SBT Test
        run: sbt test
